CREATE DATABASE IF NOT EXISTS QUIZZES;
DROP USER IF EXISTS 'QUIZZES'@'%';
CREATE USER 'QUIZZES'@'%' IDENTIFIED BY 'QUIZZES';
GRANT ALL PRIVILEGES ON QUIZZES.* TO 'QUIZZES'@'%';
FLUSH PRIVILEGES;
USE QUIZZES;
CREATE TABLE TOPIC (
    TOPIC_ID INT NOT NULL,
    NAME VARCHAR(80) NOT NULL
);
ALTER TABLE TOPIC
    ADD CONSTRAINT TOPIC_PK PRIMARY KEY (TOPIC_ID),
    MODIFY COLUMN TOPIC_ID INT NOT NULL AUTO_INCREMENT;
CREATE TABLE QUIZ (
    TOPIC_ID INT NOT NULL,
    QUIZ_ID INT NOT NULL,
    QUESTION VARCHAR(80) NOT NULL,
    ANSWER_1 VARCHAR(80) NOT NULL,
    ANSWER_2 VARCHAR(80) NOT NULL,
    ANSWER_3 VARCHAR(80) NOT NULL,
    ANSWER_4 VARCHAR(80) NOT NULL,
    CORRECT_ANSWER INT NOT NULL
);
ALTER TABLE QUIZ
    ADD CONSTRAINT QUIZ_PK PRIMARY KEY (QUIZ_ID),
    MODIFY COLUMN QUIZ_ID INT NOT NULL AUTO_INCREMENT;
CREATE TABLE GAME (
    GAME_ID INT NOT NULL,
    TOPIC_ID INT NOT NULL,
    PLAYER_NAME VARCHAR(80) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NULL,
    SCORE INT NOT NULL,
    TOTAL_TIME INT NULL
);
ALTER TABLE GAME
    ADD CONSTRAINT GAME_PK PRIMARY KEY (GAME_ID),
    MODIFY COLUMN GAME_ID INT NOT NULL AUTO_INCREMENT;
CREATE TABLE ROUND (
    ROUND_ID INT NOT NULL,
    QUIZ_ID INT NOT NULL,
    GAME_ID INT NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME NULL,
    WAS_CORRECT TINYINT(1) NULL
);
ALTER TABLE ROUND
    ADD CONSTRAINT ROUND_PK PRIMARY KEY (ROUND_ID),
    MODIFY COLUMN ROUND_ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE QUIZ
    ADD CONSTRAINT QUIZ_FK FOREIGN KEY (TOPIC_ID)
    REFERENCES TOPIC (TOPIC_ID);
ALTER TABLE GAME
    ADD CONSTRAINT GAME_FK FOREIGN KEY (TOPIC_ID)
    REFERENCES TOPIC (TOPIC_ID);
ALTER TABLE ROUND
    ADD CONSTRAINT ROUND_FK1 FOREIGN KEY (QUIZ_ID)
    REFERENCES QUIZ (QUIZ_ID);
ALTER TABLE ROUND
    ADD CONSTRAINT ROUND_FK2 FOREIGN KEY (GAME_ID)
    REFERENCES GAME (GAME_ID);